name: "ICTv8 CI/CD"

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run react npm build script
        run: npm install && npm build
        env: CI:false

      - name: FTP-Deploy-Action
        uses: SamKrikland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp.primeitclub.com
          ftp-user: ictv8-ftp-cicd@ictv8.primeitclub.com
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
